subject: "Rescue keyword"
description: "without exception but with a variable"
notes: >
  The rescue branch is represented as a RescueStandardErrorNode node
  and assigning a local variable with `$!` global variable.
focused_on_node: "org.truffleruby.language.exceptions.TryNode"
ruby: |
  begin
    "foo"
  rescue => error
    42
  end
ast: |
  TryNodeGen
      attributes:
          canOmitBacktrace = false
      children:
          rescueParts = [
              RescueStandardErrorNode
                  children:
                      rescueBody =
                          SequenceNode
                              children:
                                  body = [
                                      WriteLocalVariableNode
                                          attributes:
                                              frameSlot = 2
                                          children:
                                              valueNode =
                                                  ReadGlobalVariableNodeGen
                                                      attributes:
                                                          name = "$!"
                                                      children:
                                                          lookupGlobalVariableStorageNode =
                                                              LookupGlobalVariableStorageNodeGen
                                                                  attributes:
                                                                      index = -1
                                                                      name = "$!"
                                      IntegerFixnumLiteralNode
                                          attributes:
                                              value = 42
                                  ]
          ]
          tryPart =
              StringLiteralNode
                  attributes:
                      encoding = UTF-8
                      tstring = foo